#!/bin/sh
# 
# Ever wanted to use awk to grep for a block conditionally, based on the content inside of it? Here you go! :)
# 
# Will print all matches
#
# Usage:
#	awkblock start-pattern end-pattern query filename
#		If no filename is provided, stdin is used
#
#	awkblock query filename
#		If no filename is provided, stdin is used
#		Uses blank lines as the block pattern
#
# Dependencies:
#	- awk
# 
# Example:
#	awkblock "{" "}" "factory.name" /etc/pipewire/pipewire.conf
#	awkblock "factory.name" /etc/pipewire/pipewire.conf
# 


if [ "$#" = "4" ] || [ "$#" = "3" ] ; then
	START="$1"
	END="$2"
	QUERY="$3"
	shift 3
elif [ "$#" = "2" ] || [ "$#" = "1" ] ; then
	START="^$"
	END="^$"
	QUERY="$1"
	shift 1
else
	echo "Read the usage of the file."
fi

awk \
	'BEGIN {found=0; buf=""}
	/'"${QUERY//\//\\}"'/ { found=1; }
	/'"${START//\//\\}"'/ { if (!found) { buf="" }; }
	/'"${END//\//\\}"'/ { if (found) { found=0; print buf $0; buf=""; }; }
	{ buf = buf $0 ORS; }
' "${1:-/dev/stdin}"

