#!/bin/sh
set -e
DEFAULT_PROTOCOL="https://"  # to be used in combination with default_git
DEFAULT_GIT="github.com"
XDG_BIN_HOME="${XDG_BIN_HOME:-${HOME:?}/.local/bin}"
REPOS_HOME="$HOME/.local/src"
REPO_EXTENSION=".git"
LOG_PATH="./logs"  # will be relative to the project directory when building
UPLOAD_CMD="curl -F 'f:1=<-' -F 'ext:1=log'"
USE_SYMLINKS=1

URL="${1:?Must specify URL}"
PROJECT_NAME="${2:-$(basename "${URL}")}"

colours() {
	BLACK=$(tput setaf 0)
	RED=$(tput setaf 1)
	GREEN=$(tput setaf 2)
	YELLOW=$(tput setaf 3)
	LIME_YELLOW=$(tput setaf 190)
	POWDER_BLUE=$(tput setaf 153)
	BLUE=$(tput setaf 4)
	MAGENTA=$(tput setaf 5)
	CYAN=$(tput setaf 6)
	WHITE=$(tput setaf 7)
	BRIGHT=$(tput bold)
	NORMAL=$(tput sgr0)
	BLINK=$(tput blink)
	REVERSE=$(tput smso)
	UNDERLINE=$(tput smul)

	INFO="[${BLUE}info${NORMAL}] "
	WARN="[${YELLOW}warn${NORMAL}] "
	ERR="[${RED}err!${NORMAL}] "
	HAPPY="[${LIME_YELLOW}nice${NORMAL}] "
	CODE="\t${CYAN}"
	INLINECODE="${CYAN}"
}
colours


git_installer() {
	printf "%sAttempting a git install...\n" "${INFO}"
	REPO_TARGET="${REPOS_HOME}/${PROJECT_NAME}${REPO_EXTENSION}"
	if [ ! -e "${REPOS_HOME}" ]; then
		mkdir -p "${REPOS_HOME}"
		printf "%sCreated ${REPOS_HOME}/" "${INFO}"
	fi
	if [ ! -e "${XDG_BIN_HOME}" ]; then
		mkdir -p "${XDG_BIN_HOME}"
		printf "%sCreated ${XDG_BIN_HOME}/" "${INFO}"
	fi
	if grep -q -E "^\S+/\S+$" <<< "${URL}"; then
		URL="${DEFAULT_PROTOCOL}${DEFAULT_GIT}/${URL}"
		printf "%sAssuming ${URL}\n" "${INFO}"
	fi
		
	if [ -e "${REPO_TARGET}" ]; then
		printf "${WARN}Already found ${REPO_TARGET} on your system! Using it.\n"
		pushd "${REPO_TARGET}" >/dev/null
		printf "%sChecking for upstream updates...\n" "${INFO}"
		git fetch --quiet

		# just fail immediately if any of the tracked files are dirty
		if [ ! "$(git status --untracked-files=no --porcelain | wc -l)" -eq 0 ]; then
			printf "${ERR}You have uncommited changes! Halting.\n"
			exit 1
		fi

		# allow untracked files locally
		if [ ! "$(git status --untracked-files=all --porcelain | wc -l)" -eq 0 ]; then
			printf "%sYou have new files in the directory!\n" "${WARN}"
		fi

		# if we are not up-to-date per upstream, pull changes into local
		if ! git diff-index --quiet HEAD@{upstream} --; then
			printf "%sUpdating the source files on your system...\n" "${INFO}"
			git pull --quiet
			printf "%sUpdated the source files\n" "${HAPPY}"
		fi

	else
		git clone --quiet "${URL}" "${REPO_TARGET}"
		printf "%sCompleted download of source files...\n" "${INFO}"
		pushd "${REPO_TARGET}" >/dev/null
	fi

	if test -e "Makefile"; then
		if [ ! -e "${LOG_PATH}" ]; then
			mkdir -p "${LOG_PATH}"
			printf "%sCreated ${REPO_TARGET}/${LOG_PATH}...\n" "${INFO}"
		fi
		logfile="$(mktemp -p "${LOG_PATH}" "${PROJECT_NAME}_makelogs.XXXXX.log")"
		if make -k 2>&1 > "${logfile}"; then
			printf "%sCompleted building the executable(s)!\n" "${HAPPY}"
			printf "%sLogs of make are in ${INLINECODE}${REPO_TARGET}/${logfile}${NORMAL}\n" "${INFO}"
		else
			printf "%sRepository couldn't make the executables...\n" "${ERR}"
			printf "%sCheck the logs, or send them to someone tech-savvy!\n" "${WARN}"
			printf "%sRun the following to upload the file, and then just send the URL to your best friend!\n" "${WARN}"
			printf "%scat ${REPO_TARGET}/${logfile} | ${UPLOAD_CMD} ix.io ${NORMAL}\n" "${CODE}"
			exit 3
		fi
	else
		printf "%sRepository doesn't have a makefile... request one!\n" "${ERR}"
		exit 4
	fi

	if [ -d "./bin" ]; then
		bin_location="./bin"
	elif [ -d "./build" ]; then
		bin_location="./build"
	else
		printf "%sCould not find the directory for the binary\n" "${ERR}"
		printf "%sMaybe the makefile doesn't use ./bin/ or ./build?\n" "${WARN}"
		printf "%sIf that's the case please let me know, and I'll consider updating this program\n" "${INFO}"
		exit 4
	fi
	printf "%sFound a common location for binaries to be in...\n" "${INFO}"

	for file in "${bin_location}"/*; do
		if test -x "${file}"; then
			if test -n "${binfile}"; then
				printf "%sFound multiple executables. Halting.\n" "${ERR}"
				printf "%sLook into the ${bin_location} directory to see which one is the one you want\n" "${WARN}"
				printf "%sThen run the following:\n" "${WARN}"
				printf "${CODE}install -T ${bin_location}/the_file ${XDG_BIN_HOME}/${PROJECT_NAME}${NORMAL}\n"
				exit 5
			fi
			binfile="${file}"
		fi
	done
	printf "${INFO}Assuming the binary to be installed is ${binfile}\n"
	if [ -z "${binfile}" ]; then
		printf "%sCould not find an executable in ${bin_location}\n" "${ERR}"
		printf "%sMaybe you need to run ${CODE}chmod u+x ${bin_location}/the_file${NORMAL}\n" "${WARN}"
		printf "%sAfter that, run this:\n" "${WARN}"
		printf "%sinstall -T ${bin_location}/the_file ${XDG_BIN_HOME}/${PROJECT_NAME}${NORMAL}\n" "${CODE}"

		popd >/dev/null
		exit 6
	else
		printf "${INFO}Assuming the binary to be installed is ${binfile}\n"
		if [ -z "$USE_SYMLINKS" ] || [ "$USE_SYMLINKS" -eq 0 ]; then
			install -T "${binfile}" "${XDG_BIN_HOME}/${PROJECT_NAME}"
		else
			if [ -e "${XDG_BIN_HOME}/${PROJECT_NAME}" ]; then
				printf "%sThere is already something at ${XDG_BIN_HOME}/${PROJECT_NAME}. Halting\n" "${ERR}"
				exit 7
			fi
			ln -sT "${REPO_TARGET}/${binfile}" "${XDG_BIN_HOME}/${PROJECT_NAME}"
		fi
		printf "${HAPPY}Completed installation!\n"
		popd >/dev/null
	fi
}

http_installer() {
	if [ ! -d "${XDG_BIN_HOME}" ]; then
		mkdir -p "${XDG_BIN_HOME}"
		printf "${INFO}Created ${XDG_BIN_HOME}\n"
	fi
	printf "%sAttempting to install binary...\n" "${INFO}"
	if [ -e "${XDG_BIN_HOME}/${PROJECT_NAME}" ]; then
		printf "%s${XDG_BIN_HOME}/${PROJECT_NAME} already exists\n" "${ERR}"
		exit 8
	fi

	if ! curl -L -s "${URL}" -o "${XDG_BIN_HOME}/${PROJECT_NAME}"; then
		printf "%sFailed to download fail. Is the link valid? Do you have internet?\n" "${ERR}"
		exit 9
	fi

	printf "%sMaking the binary executable...\n" "${INFO}"
	chmod u+x "${XDG_BIN_HOME}/${PROJECT_NAME}"

	printf "%sCompleted installation of ${PROJECT_NAME}!\n" "${HAPPY}"
}


# grep cases:
#   git@... or github.com... or gitlab.com... or git://...
#   github.com/whatever/else... or www.github.com... or https://github.com...
#   whatever/else
if grep -q -E "^git|${DEFAULT_GIT}|^\w+/\w+$" <<< "${URL}"; then
	git_installer
else 
	http_installer
fi


