#!/bin/sh
printf "pstree bloat:\t" && /bin/ps -e | wc -l
printf "Home bloat:\t" && /bin/ls -1a "$HOME" | wc -l

KERNEL_CONF="/proc/config.gz"
{ zgrep '=m' "$KERNEL_CONF" | wc -l; zgrep '=y' "$KERNEL_CONF" | wc -l; zgrep 'is not set' "$KERNEL_CONF" | wc -l; } | tr '\n' ' ' | awk '{print "Modules:\t"100*$1/($1+$2+$3)"%"} {print "Built-in:\t"100*$2/($1+$2+$3)"%"}'

