#!/bin/sh
OLD=$'\033[38;5;124m'
NEW=$'\033[38;5;40m'
RESET=$'\033[0m'

OPTARGS=$(getopt --options f:t: --longoptions from:to: -- "$@")

eval set -- "$OPTARGS"
while :
	do case "$1" in
		-f | --from) FROM="$2" ; shift 2 ;;
		-t | --to) TO="$2" ; shift 2 ;;
		--) shift; break ;;
		*) echo "Wrong option passed: $1" ;;
	esac
done

[ -z "$TO" ] && [ -z "$FROM" ] && TO="/etc"
[ -z "$FROM" ] && [ "$TO" = "/etc" ] && FROM="/usr/share"
[ -z "$TO" ] && [ "$FROM" = "/usr/share" ] && TO="/etc"


echo "Original file: ${OLD}${FROM}/$1${RESET}"
echo "Current file: ${NEW}${TO}/$1${RESET}"
echo ""

diff \
		 --unchanged-line-format="" \
		 --old-line-format="${OLD}%dn:${RESET} %L" \
		 --new-line-format="${NEW}%dn:${RESET}: %L" \
		 --from-file "${FROM}/$1" \
		 "${TO}/$1"
		 
