#!/usr/bin/env sh

REALHOME=$HOME
FAKEHOME=$HOME/.local/fakehomes # Replace this with where you want it to be
RUNELITE_EXEC=~/.local/gits/runelite/launcher.git/target/RuneLite.jar

# Adds symlinks for actual paths in fakehome
remember() {
	# Replace OLDHOME with HOME in the link name
	fake_dir=$(echo $1 | sed "s:^$REALHOME:$FAKEHOME:")
	echo -en "Relinking '$1' to '$fake_dir'... "

	# Creates the link's parent directory and symlinks it
	mkdir -p $(dirname $fake_dir) || echo "Failed to create parent dirs"
	ln -s "$1" -t "$(dirname ${fake_dir})" 2> /dev/null
	ret=$?
	[ "$ret" -eq "0" -o "$ret" -eq "1" ] && return 0 || return 1
}
forget() {
	fake_dir=$(echo $1 | sed "s:^$REALHOME:$FAKEHOME:" | sed 's:^\(.*\)/$:\1:')
	echo -en "Unlinking '$fake_dir'... "
	unlink "$fake_dir" 2> /dev/null
	ret=$?
	[ "$ret" -eq "0" -o "$ret" -eq "1" ] && return 0 || return 1
}

try() {
	$@
	ret=$?
	[ "$ret" -eq "0" ] && echo "Ok" || echo "Failed" 
	[ "$ret" -eq "0" ] || export error=1
}

mkdir -p $FAKEHOME
paths() {
	try $1 ${XDG_DATA_HOME:-$HOME/.local/share}
	try $1 ${XDG_CACHE_HOME:-$HOME/.cache}
	try $1 ${XDG_CONFIG_HOME:-$HOME/.config}
	try $1 ${REALHOME}/.icons # ~/.icons (lxappearance's mouse cursor theme)
}
move_directory() {
	should_move_directory=1
	[ -d $REALHOME/.runelite ] && [ ! -d $FAKEHOME/.runelite ] && should_move_directory=1 || return 0
	[ "$should_move_directory" -eq "1" ] && echo "Moving '$REALHOME/.runelite' to '$FAKEHOME/.runelite'" && mv --target-directory=$FAKEHOME -- $REALHOME/.runelite && return 0

}
main() {
	export HOME=${FAKEHOME}

	error=0
	paths remember || error=1
	move_directory || error=1

	[ "$error" = "0" ] && java -jar $RUNELITE_EXEC "$@" || echo "Failed to fakehome runelite"
}

main
