#!/bin/sh
# reads your history file, taking the second last command (last one is this command, heh)
# strips the first command with sed because zsh adds some metadata in the format of `: $(date +"%s");`
input="$(cat $XDG_CACHE_HOME/zsh/history | tail -n2 | head -n1 | sed "s/\([^;]*\);\(.*\)/\2/")"

# no filename means you're being silly
[ -z "$1" ] && exit 1

# saves to ~/.local/bin/ as per XDG specification (why doesn't this have a $XDG_BIN_HOME or something?), and makes it executable
[ ! -e "$HOME/.local/bin/$1" ] && echo -e "#!/bin/sh\n'$input'" > $HOME/.local/bin/$1 && chmod +x $HOME/.local/bin/$1 && echo "saved '$input' in $HOME/.local/bin/$1"

