#!/bin/sh

export TERM=${TERM:-xterm-256color}
IFS='
'

for session in $(tmux list-sessions -F"#S"); do
        printf "%s\n" "${session}"
        for window in $(tmux list-windows -F"#W" -t "${session}"); do
                printf "├── %s\n" "${window}"
                for pane in $(tmux list-panes -t "${session}:${window}" -F"#T"); do
                        printf "│  ├── %s\n" "${pane}"
                done
                tput cuu1
                printf "│  └\n"
        done
        tput cuu1
        printf "└\n  \n"
done

