#!/bin/sh
# Do you forget where you placed your windows sometimes?
#
# Just exec this program from your sway config in a binding,
# and get ready to search through them with wofi! :)
#

window="$(swaymsg -t get_tree -r |
	jq -r 'recurse(.nodes[]) | select(.type != "workspace" and .type != "output") | .name' | \
	wofi --dmenu --insensitive )" 

swaymsg -t get_tree -r | jq \
	--arg window "${window:?You did not select any window}" 
	'recurse(.nodes[]) | select(.name == $window) | .id' | \
		xargs -I{} swaymsg "[con_id={}]" focus

